# Generated by Django 5.0.7 on 2025-06-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
